<h3 id="termdescription" style="text-align: left; line-height: normal; widows: 2; text-transform: none; background-color: #ffffff; font-variant: normal; font-style: normal; text-indent: 0px; margin: 0px; outline-style: none; outline-color: invert; outline-width: 0px; font-family: Verdana, Geneva, Kalimati, sans-serif; white-space: normal; orphans: 2; letter-spacing: normal; color: #4f3131; vertical-align: baseline; word-spacing: 0px; border: 0px; padding: 0px;">The following Terms and Conditions apply to the use of this Web site as well as all transactions conducted through the site.</h3>
<ul id="termsandconditions" style="text-align: left; widows: 2; text-transform: none; background-color: #ffffff; list-style-type: none; text-indent: 0px; margin: 0px; outline-style: none; outline-color: invert; outline-width: 0px; font: 12px Verdana, Geneva, Kalimati, sans-serif; white-space: normal; orphans: 2; letter-spacing: normal; color: #4f3131; vertical-align: baseline; word-spacing: 0px; border: 0px; padding: 0px;">
<li class="termtitle" style="margin: 0px; outline-style: none; outline-color: invert; outline-width: 0px; vertical-align: baseline; border: 0px; padding: 0px;"><span style="text-decoration: underline;">Privacy Policy</span></li>
<li class="termbody" style="margin: 0px; outline-style: none; outline-color: invert; outline-width: 0px; vertical-align: baseline; border: 0px; padding: 0px;">
<div class="qsc" style="margin: 0px; outline-style: none; outline-color: invert; outline-width: 0px; vertical-align: baseline; border: 0px; padding: 0px;">
<p><span class="Apple" style="margin: 0px; outline-style: none; outline-color: invert; outline-width: 0px; font-family: arial, helvetica, sans-serif; white-space: pre-wrap; font-size: small; vertical-align: baseline; border: 0px; padding: 0px;">We use the information you provide about yourself when placing an order only to complete that order. We do not share this information with outside parties except to the extent necessary to complete that order. <br /><br />We use the information you provide about someone else when placing an order only to ship the product and to confirm delivery. We do not share this information with outside parties except to the extent necessary to complete that order. <br /><br />We use return email addresses to answer the email we receive. Such addresses are not used for any other purpose and are not shared with outside parties. <br /><br />You can register with our website if you would like to receive our catalog as well as updates on our new products and services. Information you submit on our website will not be used for this purpose unless you fill out the registration form. <br /><br />We use non-identifying and aggregate information to better design our website and to share with advertisers. For example, we may tell an advertiser that X number of individuals visited a certain area on our website, or that Y number of men and Z number of women filled out our registration form, but we would not disclose anything that could be used to identify those individuals. <br /><br />Finally, we never use or share the personally identifiable information provided to us online in ways unrelated to the ones described above without also providing you an opportunity to opt-out or otherwise prohibit such unrelated uses.</span></p>
</div>
</li>
<br /><br />
<li class="termtitle" style="margin: 0px; outline-style: none; outline-color: invert; outline-width: 0px; vertical-align: baseline; border: 0px; padding: 0px;"><span style="text-decoration: underline;">Shipping &amp; Delivery</span></li>
<li class="termbody" style="margin: 0px; outline-style: none; outline-color: invert; outline-width: 0px; vertical-align: baseline; border: 0px; padding: 0px;">
<div class="qsc" style="margin: 0px; outline-style: none; outline-color: invert; outline-width: 0px; vertical-align: baseline; border: 0px; padding: 0px;">
<p><span class="Apple" style="margin: 0px; outline-style: none; outline-color: invert; outline-width: 0px; font-family: arial, helvetica, sans-serif; white-space: pre-wrap; font-size: small; vertical-align: baseline; border: 0px; padding: 0px;">Please allow 1-2 business days for orders to be processed and shipped out. Once shipped please allow 3-7 days for shipment to arrive.</span></p>
<p><br /><span style="margin: 0px; outline-style: none; outline-color: invert; outline-width: 0px; font-family: arial, helvetica, sans-serif; font-size: small; vertical-align: baseline; border: 0px; padding: 0px;">Orders are shipped through the United States Post Office and FedEx.</span></p>
<p><span class="Apple" style="margin: 0px; outline-style: none; outline-color: invert; outline-width: 0px; font-family: arial, helvetica, sans-serif; white-space: pre-wrap; font-size: small; vertical-align: baseline; border: 0px; padding: 0px;">In the event that an order arrives damaged or is not delivered, notification must be made within 21 days of the shipment date in order to file an insurance claim and reship the items to you.</span></p>
<p><span class="Apple" style="margin: 0px; outline-style: none; outline-color: invert; outline-width: 0px; font-family: arial, helvetica, sans-serif; white-space: pre-wrap; font-size: small; vertical-align: baseline; border: 0px; padding: 0px;">In the event that 3 or more items are damaged in transit pictures may be required as proof of damage for insurance purposes. Failure to provide pictures within 7 days of request will result in a decline of insurance.</span></p>
<p><span class="Apple" style="margin: 0px; outline-style: none; outline-color: invert; outline-width: 0px; font-family: Verdana, Arial, Helvetica, sans-serif; white-space: pre-wrap; font-size: 10px; vertical-align: baseline; border: 0px; padding: 0px;"><span style="margin: 0px; outline-style: none; outline-color: invert; outline-width: 0px; font-family: arial, helvetica, sans-serif; font-size: small; vertical-align: baseline; border: 0px; padding: 0px;">Do not refuse a package due to damage. Accept the package and photograph the damage for insurance purposes. If the package is refused a claim may not be filed if the package does not get returned. This is due to being unable to prove package was refused due to damage.</span></span></p>
<p><span class="Apple" style="margin: 0px; outline-style: none; outline-color: invert; outline-width: 0px; font-family: Verdana, Arial, Helvetica, sans-serif; white-space: pre-wrap; font-size: 10px; vertical-align: baseline; border: 0px; padding: 0px;"><span style="margin: 0px; outline-style: none; outline-color: invert; outline-width: 0px; font-family: arial, helvetica, sans-serif; font-size: small; vertical-align: baseline; border: 0px; padding: 0px;">Orders over $200 will automatically have signature required for the package. <br /></span></span></p>
</div>
</li>
<br /><br />
<li class="termtitle" style="margin: 0px; outline-style: none; outline-color: invert; outline-width: 0px; vertical-align: baseline; border: 0px; padding: 0px;"><span style="text-decoration: underline;">Sales Tax</span></li>
<li class="termbody" style="margin: 0px; outline-style: none; outline-color: invert; outline-width: 0px; vertical-align: baseline; border: 0px; padding: 0px;">
<div class="qsc" style="margin: 0px; outline-style: none; outline-color: invert; outline-width: 0px; vertical-align: baseline; border: 0px; padding: 0px;">
<p><span class="Apple" style="margin: 0px; outline-style: none; outline-color: invert; outline-width: 0px; font-family: arial, helvetica, sans-serif; white-space: pre-wrap; font-size: small; vertical-align: baseline; border: 0px; padding: 0px;">Zafran Perfumes&nbsp;charges sales tax for merchandise ordered on this Web site based on the applicable state sales tax rate and the location to which the order is being shipped.</span></p>
</div>
</li>
<br /><br />
<li class="termtitle" style="margin: 0px; outline-style: none; outline-color: invert; outline-width: 0px; vertical-align: baseline; border: 0px; padding: 0px;"><span style="text-decoration: underline;">Return Policy</span></li>
<li class="termbody" style="margin: 0px; outline-style: none; outline-color: invert; outline-width: 0px; vertical-align: baseline; border: 0px; padding: 0px;">
<div class="qsc" style="margin: 0px; outline-style: none; outline-color: invert; outline-width: 0px; vertical-align: baseline; border: 0px; padding: 0px;">
<p><span style="margin: 0px; outline-style: none; outline-color: invert; outline-width: 0px; font-family: arial, helvetica, sans-serif; font-size: small; vertical-align: baseline; border: 0px; padding: 0px;">If you are not satisfied with any unused oil simply mail it back within 30 days from the order date.</span></p>
<p><span style="margin: 0px; outline-style: none; outline-color: invert; outline-width: 0px; font-family: arial, helvetica, sans-serif; font-size: small; vertical-align: baseline; border: 0px; padding: 0px;">The return can either be exchanged at no cost, or refunded after a 25% restocking fee.&nbsp; Shipping &amp; Handling is non-refundable.</span></p>
<p><span style="margin: 0px; outline-style: none; outline-color: invert; outline-width: 0px; font-family: arial, helvetica, sans-serif; font-size: small; vertical-align: baseline; border: 0px; padding: 0px;">Please include a copy of the invoice and a note requesting either a refund or an exchange.&nbsp; If exchanging please include what items requested for the exchange.<br /></span></p>
<p>&nbsp;</p>
<p><span style="margin: 0px; outline-style: none; outline-color: invert; outline-width: 0px; font-family: arial, helvetica, sans-serif; font-size: small; vertical-align: baseline; border: 0px; padding: 0px;">Customers are responsible for shipping &amp; handling charges associated with returns anc exchanges.<br /></span></p>
<p><span style="margin: 0px; outline-style: none; outline-color: invert; outline-width: 0px; font-family: arial, helvetica, sans-serif; font-size: small; vertical-align: baseline; border: 0px; padding: 0px;">Scented products that are not 100% oil cannot be returned.&nbsp; For example Scented Body Wash, Scented Shampoo, etc...</span></p>
</div>
</li>
<br /><br />
<li class="termtitle" style="margin: 0px; outline-style: none; outline-color: invert; outline-width: 0px; vertical-align: baseline; border: 0px; padding: 0px;"><span style="text-decoration: underline;">Miscellaneous</span></li>
<li class="termbody" style="margin: 0px; outline-style: none; outline-color: invert; outline-width: 0px; vertical-align: baseline; border: 0px; padding: 0px;">
<div class="qsc" style="margin: 0px; outline-style: none; outline-color: invert; outline-width: 0px; vertical-align: baseline; border: 0px; padding: 0px;">
<p style="widows: 2; text-transform: none; background-color: #ffffff; text-indent: 0px; font: 10px Verdana, Arial, Helvetica, sans-serif; white-space: normal; orphans: 2; letter-spacing: normal; color: #000000; word-spacing: 0px;"><span style="margin: 0px; outline-style: none; outline-color: invert; outline-width: 0px; font-family: arial, helvetica, sans-serif; font-size: small; vertical-align: baseline; border: 0px; padding: 0px;">By placing an order you are agreeing that the items purchased and information provided for the order and address information are accurate.&nbsp; Any errors and costs associated with correcting and/or caused by those errors are the responsibility of the person(s) placing the order.</span></p>
<p style="widows: 2; text-transform: none; background-color: #ffffff; text-indent: 0px; font: 10px Verdana, Arial, Helvetica, sans-serif; white-space: normal; orphans: 2; letter-spacing: normal; color: #000000; word-spacing: 0px;">&nbsp;</p>
<p style="widows: 2; text-transform: none; background-color: #ffffff; text-indent: 0px; font: 10px Verdana, Arial, Helvetica, sans-serif; white-space: normal; orphans: 2; letter-spacing: normal; color: #000000; word-spacing: 0px;"><span style="margin: 0px; outline-style: none; outline-color: invert; outline-width: 0px; font-family: arial, helvetica, sans-serif; font-size: small; vertical-align: baseline; border: 0px; padding: 0px;">CANCELATION FEE:&nbsp; There is a 10% Cancelation fee for order that have been filled and requested to cancel before picked up for shipping</span></p>
<p style="widows: 2; text-transform: none; background-color: #ffffff; text-indent: 0px; font: 10px Verdana, Arial, Helvetica, sans-serif; white-space: normal; orphans: 2; letter-spacing: normal; color: #000000; word-spacing: 0px;"><span style="margin: 0px; outline-style: none; outline-color: invert; outline-width: 0px; font-family: arial, helvetica, sans-serif; font-size: small; vertical-align: baseline; border: 0px; padding: 0px;">VOID WHERE PROHIBITED: Although the information on this Web site is accessible worldwide, not all products or services discussed in this Web site are available to all persons or in all geographic locations or jurisdictions. Zafran Perfumes reserve the right to limit the provision of their products or services to any person, geographic area, or jurisdiction they so desire and to limit the quantities of any products or services that they provide. Any offer for any product or service made in the materials on this Web site is void where prohibited.</span></p>
<p style="widows: 2; text-transform: none; background-color: #ffffff; text-indent: 0px; font: 10px Verdana, Arial, Helvetica, sans-serif; white-space: normal; orphans: 2; letter-spacing: normal; color: #000000; word-spacing: 0px;"><span style="margin: 0px; outline-style: none; outline-color: invert; outline-width: 0px; font-family: arial, helvetica, sans-serif; font-size: small; vertical-align: baseline; border: 0px; padding: 0px;">MISCELLANEOUS: The Terms and Conditions constitute the entire agreement between you and The Common Scents, Inc. with respect to this Web site. The Terms and Conditions supercede all prior or contemporaneous communications and proposals, whether electronic, oral or written between you and Zafran Perfumes. with respect to this Web site. No modification of the Terms and Conditions shall be effective unless it is authorized by The Zafran Perfumes. If any provision of the Terms and Conditions is found to be contrary to law, then such provision(s) shall be constructed in a manner to closely reflect, as much as possible, the intentions of the parties, with the other provisions remaining in full force and effect.</span></p>
</div>
</li>
<br /> 
</ul>